### ISSUE TITLE
phpseclib error on laravel ^8.12

### ISSUE THREAD

**Issue by alirxamughal** [hyn/multi-tenant#1002]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - hyn/multi-tenant[5.7.0, ..., 5.x-dev] require phpseclib/phpseclib ~2.0 -> found phpseclib/phpseclib[2.0.0, ..., 2.0.x-dev] but the package is fixed to 3.0.8 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires hyn/multi-tenant ^5.7 -> satisfiable by hyn/multi-tenant[5.7.0, 5.7.1, 5.7.2, 5.x-dev].

**Comment by bkintanar** [comment]
This should be fixed when we release Laravel 8 support.

**Comment by mikebronner** [comment]
@bkintanar Hi, I still appear to be getting this issue when trying to use the PHP 8.0 compatible release:

```
Problem 1
    - hyn/multi-tenant[5.7.3, ..., 5.x-dev] require phpseclib/phpseclib ~2.0 -> found phpseclib/phpseclib[2.0.0, ..., 2.0.x-dev] but the package is fixed to 3.0.9 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - hyn/multi-tenant[5.7.0, ..., 5.7.2] require php ^7.3 -> your php version (8.0.0) does not satisfy that requirement.
    - Root composer.json requires hyn/multi-tenant ^5.7 -> satisfiable by hyn/multi-tenant[5.7.0, ..., 5.x-dev].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
```  

**Update for anyone running into this** I was able to work around this by deleting the `vendor` folder and the `composer.lock` file and running `composer update` from scratch.

**Comment by bkintanar** [comment]
@mikebronner I think there was an updated phpseclib that needed the update as well. That's why composer suggested to run composer with --with-all-dependencies to allow upgrades.
