### ISSUE TITLE
Table 'hostnames' doesn't exist after migrate:reset

### ISSUE THREAD

**Issue by paishin** [hyn/multi-tenant#380]
After running php artisan migrate:reset I get the following error whenever I try to run any artisan commands

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'overwatch.hostna  
  mes' doesn't exist (SQL: select * from `hostnames` where `fqdn` = localhost  
   limit 1)  .

I guess that is because it tries to identify which database to load, but I can't figure out how to fix it.

**Comment by luceos** [comment]
Hostnames is part of system. I'm unsure why it would not reset. Maybe you need to run `php artisan tenancy:install`?

**Comment by paishin** [comment]
I can't any more, since every command produces the above error, even 'php artisan list'.

The only way I have found to bypass this problem is manually creating a 'tenant' table with the field fqdn 
in it and then edit  '2017_01_01_000005_tenancy_hostnames.php' to add Schema::dropIfExists('hostnames'); on line 25 (otherwise I would get a table already exists error when migrating)... and then run php artisan migrate:refresh

Although this works, its a hack, not a solution.

**Comment by luceos** [comment]
In case you have a `tenancy.json` file in your laravel root path, delete that and run `php artisan tenancy:install`. I hope that solves it.

**Comment by paishin** [comment]
That didn't help.

My guess is that the hostnames table is always queried when tried to select a database to use during artisan commands but because during the reset all tables are deleted this error is shown.

I don't know where exactly this happens, it would be helpfull if I could see the stack trace, but using -v doesnt show anything for sql errors.

**Comment by Thijmen** [comment]
`php artisan command:list -vvv` gives more verbose output.

**Comment by Wijnands** [comment]
I have the same problem.
When i clone my application to the server and try to install with the command tenancy:install

I can't firuge out how to solve this. The only solution was to create all the tables by hand.

**Comment by Thijmen** [comment]
@Wijnands Make sure you don't commit the `tenancy.json` file.

**Comment by Wijnands** [comment]
@Thijmen The tenacy.json is not commited. Thats wy i need to intall the tenancy.

**Comment by Thijmen** [comment]
So, if you pull your app and run `php artisan tenancy:install` before anything else, you'll end up with the `hostname doesnt exist` error?

**Comment by Wijnands** [comment]
@Thijmen this is what i do when i pull my app.
- composer install
- cp .env.example .env
- php artisan key:generate
- changed .env file whit the correct settings/value for database settings
- php artisan tenancy:install

 SQLSTATE[42S02]: Base table or view not found: 1146 Table 'test.hostnames' doesn't exist 

if i try to run php artisan or whatever other command the same error appear.

**Comment by Thijmen** [comment]
Which version of tenancy are you exactly using? Or post your composer.lock, maybe I can figure something out.

**Comment by luceos** [comment]
When your run migrate:reset it will drop all tables, but only migrate based on the published migration files. Tenancy does not publish its migrations by default. So you will need to run the tenancy:install command again, which won't run migrations unless you delete the tenancy.json.

Please understand that a fix is in dev-master, which needs a changelog and migrations before being tagged to 5.1.

**Comment by Wijnands** [comment]
@Thijmen the version is 5.0.17

@luceos in my application the tenancy.json file is not commited. If i run the tenancy:install command i get the same error: Base table or view not found: 1146 Table 'test.hostname'doens't exist.

**Comment by paishin** [comment]
@luceos, thank you for your comment. I was able to restore my application using your guideline. I have spent so much time trying to debug and trace the error and in the end it was a simple solution such as deleting the tenancy.json.

So to make a long story short to reset the database I have to migrate:reset, then delete tenancy.json and then re-run tenancy:install.

To make it easier I have added the following to my scripts in package.json to automate the process:
`"ResetDB": "php artisan migrate:reset && del tenancy.json &&php artisan tenancy:install",`

Once again, thank you

**Comment by michaeldaly** [comment]
I have the same issues too...I had to work around it by manually creating the hostnames table in the db, then I was able to continue as normal.

What's weird is when I deployed to a server, composer update or php artisan would not run until I manually installed the hostnames table.

**Comment by paishin** [comment]
@michaeldalyuk, what happened to me was that I was stuck in a limbo state where the application needed the hostnames table to exist in order to run but was failing to install because the hostnames table already existed. 

Try manually adding the table and then run the command I posted above and see if it helps you reset to a stable state.

**Comment by michaeldaly** [comment]
@paishin Ok thanks for the tip, I will give it a try next time I deploy to a new environment.

I even tried to ignore the package in the auto-discovery but that didn't help either - if your code works then maybe it's the way to handle this scenario moving forward.

Thanks

**Comment by luceos** [comment]
This will most likely be solved in the upcoming 5.1. Feel free to try 5.x-dev to see if that helps.

**Comment by michaeldaly** [comment]
@luceos I tried the latest version but the problem still exists.

If you give it a try do you receive the same erorr?

**Comment by luceos** [comment]
@michaeldalyuk you could publish the migration files by manually copying them over into the migrations directory you use for your system migrations. This issue wasn't resolved in 5.1.

**Comment by musioks** [comment]
removing the tenancy.json file solved my issue
