### ISSUE TITLE
routes/tenants.php is not loaded during tests, because there's no tenant, when app initializes

### ISSUE THREAD

**Issue by Plytas** [hyn/multi-tenant#584]
Don't want this to get lost in discord.

Currently `routes/tenants.php` is being loaded during boot of service providers and it checks for a tenant. My tests and tenant is being set up after that and since json request in tests do not actually create a new app, tenant routes are never defined.

Would it be possible to have callable function to load routes during runtime?

---
__Information__

- hyn/multi-tenant version: 5.2
- laravel version: 5.6

**Comment by sadnub** [comment]
I have been playing around with this.

You can set a default tenant in phpunit.xml
<env name="TENANCY_DEFAULT_HOSTNAME" value="testing.fqdn"/>

And it will fallback to this tenant. I then create a Hostname/Website matching this fqdn in the system database and all of my tenant.php routes are triggering.

**Comment by Plytas** [comment]
Nice find! But I feel like there should be a better solution to this. Forcing a tenant does not help while testing system stuff.

**Comment by luceos** [comment]
So your request is to allow the tenants.php routes file to be loaded whenever a (first) tenant was identified contrary to trying to do load those routes only during the request cycle?

**Comment by Plytas** [comment]
That's just an idea. The issue is that it's not loaded during tests.

**Comment by luceos** [comment]
We could refresh the Router object inside IoC to force the routes... I'm not sure though, it's pretty invasive for something used in tests alone.. Your tests can also refresh the router:

```php
$router = $this->app->refresh('router');
```

^ guess

**Comment by Plytas** [comment]
Thanks, I will check that out when I get the chance. I'll let you know how it goes.

**Comment by luceos** [comment]
@Plytas please do, otherwise I'll make sure to come up with a more decent solution. PLease note that testability is something I'll be looking into for the future.

**Comment by Plytas** [comment]
Looks like refresh method takes 3 parameters.  Couldn't figure out what to pass there...
```PHP
/**
 * Refresh an instance on the given target and method.
 *
 * @param  string  $abstract
 * @param  mixed   $target
 * @param  string  $method
 * @return mixed
 */
public function refresh($abstract, $target, $method)
{
	return $this->rebinding($abstract, function ($app, $instance) use ($target, $method) {
		$target->{$method}($instance);
	});
}
```
I took the logic from your `RouteProvider.php` and implemented it into my tests for now. Official solution is still welcome ;)

**Comment by Sti3bas** [comment]
@Plytas could you please share your solution? I’m also struggling with this problem.

**Comment by Plytas** [comment]
@Sti3bas I took this code from `RouteProvider.php` and ran it after I set a tenant for my tests.
```PHP
/** @var Repository $config */
$config = $this->app->make(Repository::class);
$path = $config->get('tenancy.routes.path');

/** @var Router $router */
$router = $this->app->make(Router::class);

if ($path && file_exists($path)) {
	if ($config->get('tenancy.routes.replace-global')) {
		$router->setRoutes(new RouteCollection());
	}

	$router->middleware([])->group($path);
}
```

**Comment by luceos** [comment]
@Plytas have you tried calling the RouteProvider instead?

```php
app(RouteProvider::class)->boot()
```

**Comment by Sti3bas** [comment]
@Plytas thank you. The routes are registered, but seems like `route('route-name')` helper is not working.

@luceos `app(\Hyn\Tenancy\Providers\Tenants\RouteProvider::class)->boot();` throws an exception `Illuminate\Contracts\Container\BindingResolutionException: Unresolvable dependency resolving [Parameter #0 [ <required> $app ]] in class Illuminate\Support\ServiceProvider`

**Comment by luceos** [comment]
Woops, how about this:

```php
use Hyn\Tenancy\Providers\Tenants\RouteProvider;


(new RouteProvider(app()))->boot();
```

**Comment by Sti3bas** [comment]
@luceos it works, but the problem with `route()` helper still remains.

**Comment by luceos** [comment]
Ah, yes the `url` binding has to be rebound with the new RouteCollection..

**Comment by luceos** [comment]
@Sti3bas i've pushed a commit to 5.x related to that:

https://github.com/hyn/multi-tenant/commit/8419caa34ebe26a56340a25f533a9d0f1cbfe2fd#diff-9a7853c6c8656adb4828f621b3f1faa4R51

**Comment by Sti3bas** [comment]
@luceos still doesn't work, but I've found that it works if you call `$router->getRoutes()->refreshNameLookups();`.

**Comment by luceos** [comment]
@Sti3bas please provide a snippet as example.

Never mind, I noticed. Committed some changes.

**Comment by Sti3bas** [comment]
@luceos here is the example of passing test on the fresh copy of Laravel 5.7.

routes/tenants.php:

```php
Route::get('/test-route', function () {
    return 'test';
})->name('test');
```

Hyn\Tenancy\Providers\Tenants\RouteProvider:

```php
class RouteProvider extends ServiceProvider
{
    public function boot()
    {
        /** @var Repository $config */
        $config = $this->app->make(Repository::class);
        $path = $config->get('tenancy.routes.path');

        /** @var Router $router */
        $router = $this->app->make(Router::class);

        if ($path) {
            /** @var Hostname $hostname */
            $hostname = $this->app->make(CurrentHostname::class);

            if ($hostname && file_exists($path)) {
                $this->app->booted(function () use ($config, $router, $path) {
                    if ($config->get('tenancy.routes.replace-global')) {
                        $router->setRoutes(new RouteCollection());
                    }

                    $router->middleware([])->group($path);
                    $router->getRoutes()->refreshNameLookups();
                });
            }
        }
    }
}
```

Tests\TestCase.php:

```php
public function setUp()
{
    parent::setUp();

    config([
        'tenancy.hostname.default' => 'test.tenant.test',
    ]);

    $website = new Website;
    app(WebsiteRepository::class)->create($website);

    $hostname = new Hostname();
    $hostname->fqdn = 'test.tenant.test';
    app(HostnameRepository::class)->attach($hostname, $website);

    (new RouteProvider(app()))->boot();
}
```

Tests\Feature\ExampleTest.php:

```php
class ExampleTest extends TestCase
{
    use RefreshDatabase;
    
    /**
     * A basic test example.
     *
     * @return void
     */
    public function testBasicTest()
    {
        $response = $this->get(route('test'));

        $response->assertStatus(200);
    }
}
```

**Comment by luceos** [comment]
Try 5.3.0.

Previous suggestion to call the RouteProvider is still my recommendation @Plytas 

Closing.

**Comment by Sti3bas** [comment]
@luceos just tested 5.3.0 and the above test is passing. Thank you!

**Comment by Plytas** [comment]
Yeah, all good now using RouteProvider boot method.

**Comment by luceos** [comment]
@Plytas glad to hear and glad it's pretty straightforward too.
