### ISSUE TITLE
Storage::disk('tenant') : UUID twice in path

### ISSUE THREAD

**Issue by xalunda** [hyn/multi-tenant#718]
Hi,

__Description__

I'm trying to create a file within a tenant's folder, using the documentation example:

```
Storage::disk('tenant')->put('readme.md', 'Hi John.');
```

My `tenancy.php` config is set as:
```
'disk' => 'tenant',
'auto-create-tenant-directory' => true,
'auto-rename-tenant-directory' => true,
'auto-delete-tenant-directory' => false,
```

My `filesystems.php` config has:
```
'disks' => [
    'tenant' => [
        'driver' => 'local',
        'root' => storage_path('app/public/tenancy'),
        'url' => env('APP_URL').'/storage',
        'visibility' => 'public',
    ],
    ...
]
```

---

__Actual behavior__

The file `readme.md` is created in:
```
/storage/app/public/tenancy/_UUID_/_UUID_/readme.md
```

---

__Expected behavior__

I would expect `readme.md` to be created in:
```
/storage/app/public/tenancy/_UIID_/readme.md
```

---

__Information__

- hyn/multi-tenant version: 5.3.1
- laravel version: 5.7.22
- database driver and version: MySQL 5.7.24
- php version: 7.2.1

Is there something I missed? Forgot?

**Comment by luceos** [comment]
The code will create a disk called tenant on runtime. Because you also named the disk that the runtime code will pick up the configured root and append the UUID. Because it re-uses the tenant disk every time, each time the disk is resolved the UUID is added.

A solution is to configure `disk` to be `tenants` and rename your `filesystems.disks.tenant` to `tenants`. That should solve this issue.

**Comment by xalunda** [comment]
Hi,

Renaming my disk to whatever but `tenant` worked 👍 

Thanks for your fast reply!

**Comment by decodewebin** [comment]
I guess this issue is not resolved yet. Even I am getting same problem.
